### ISSUE TITLE
Changed PredictIt API / authentication issues

### ISSUE THREAD

**Issue by michaeldickens** [kcinnick/pyredictit#1]
Thank you for writing this tool! I was trying to set up the repo and get it to work, but it appears that PredictIt has nontrivially changed its API. I tried updating your code to use the new API endpoints, but I ran into some trouble. I don't know much about web development, but it looks like as a prerequisite to putting in a buy order, the browser makes a GET request to https://www.predictit.org/api/Trade/<id>/OrderBook. Python returns a 401 when I try to hit this URL; and even when I try to hit it directly in the browser, on a session where I'm logged in, I get a 401. Don't know why that's happening, but presumably there's some sort of authentication that happens on the contracts page where you can only proceed if you're on that page? Would appreciate if you could take a look and see if you can tell what's going on.

Here's my updated function that attempts to use the new API:

    def buy_shares(self, api, number_of_shares, buy_price):
        # this URL is wrong, it's not self.cid, it's some other id, not sure what it's an id for. but it doesn't
        # work with the correct id either (I tried it directly in the browser)
        order_book_page = api.browser.get(f'https://www.predictit.org/api/Trade/{self.cid}/OrderBook')
        all_bids_and_offers = order_book_page.json()

        confirm = api.browser.post(f'https://www.predictit.org/api/Trade/ConfirmTrade', {
            'quantity': number_of_shares,
            'pricePerShare': buy_price,
            'contractId': self.cid,
            'tradeType': 1,
        })
        if str(confirm.status_code) != '200':
            print(f"Request returned an invalid {confirm.status_code} code. Please make sure you're using valid login credentials.")

**Comment by kcinnick** [comment]
Hey Michael,

There is a possibility that PredictIt has changed it's endpoints since I wrote that function.  I'll have to get creative to test this out, but should be able to at least take a look at it tonight.

Thanks,
Nick

**Comment by michaeldickens** [comment]
Following up on this... no rush or anything, I know this is just a side project so I don't expect you to invest tons of time into it. Could you just let me know when you expect to be able to get it working?

**Comment by kcinnick** [comment]
Hey Michael,

Unfortunately PredictIt asked (and I refused) to take down this repo and in return they shut down my account.  Until further notice (aka, until I find some sort of solution) I can't meaningfully test or work on this script right now.  I'll look into some options and hopefully have an update soon.

**Comment by kcinnick** [comment]
@ApologeticDoctor assuming this q's for me - I wasn't, but the majority of recent bets had been weird stuff testing out the script so I don't think I had much in there. Oh well :P

**Comment by ghost** [comment]
> @ApologeticDoctor assuming this q's for me - I wasn't, but the majority of recent bets had been weird stuff testing out the script so I don't think I had much in there. Oh well :P

I'm glad you didn't have much in there but it's ridiculous that they just stole your money!
