### ISSUE TITLE
sell_shares() is creating buy offers

### ISSUE THREAD

**Issue by spyjdh** [kcinnick/pyredictit#10]
Not great for a stop loss code lol

**Comment by spyjdh** [comment]
Meanwhile buy_at is working as intended

**Comment by spyjdh** [comment]
This is my monitor;
while True:
    pyredictit_api.get_my_contracts()
    i=0
    while i < len(pyredictit_api.my_contracts):
        pyredictit_api.monitor_price_of_contract(contract=pyredictit_api.my_contracts[i], monitor_type='detailed',
                                                 number_of_shares=0, trigger_price=0.00)
        pyredictit_api.monitor_price_of_contract(contract=pyredictit_api.my_contracts[i], monitor_type='stop_loss',
                                                 number_of_shares=pyredictit_api.my_contracts[i].number_of_shares -1, trigger_price=(float(pyredictit_api.my_contracts[i].avg_price) - 0.01))
        i += 1
    sleep(30)

**Comment by kcinnick** [comment]
do you usually code in java or something? just curious based on the while i <len(contracts) structure. Either way, can you confirm that this is the layout of your code? Since the formatting didn't transfer over in the comment I put my guess at it here:

https://github.com/kcinnick/pyredictit/blob/master/error_helping/spyjdh_error1.py

**Comment by kcinnick** [comment]
Unless PredictIt has changed their internal API, I'm hard pressed to see how L161 could create a buy offer.. going to test locally shortly

**Comment by kcinnick** [comment]
also, what's the cid of the contract where you're getting the error? Shouldn't matter but I'd like to recreate as close as possibel

**Comment by kcinnick** [comment]
Was able to re-create, going to try and figure this out before I go to sleep tonight.. will update

**Comment by kcinnick** [comment]
I see what happened. They changed the internals of the API. Working on a fix now.

**Comment by spyjdh** [comment]
Yes, most of my experience is in java. The sleep(30) is outside the second while loop but other than that looks like what I have. I, also had to change some line in the Contract class to make it work;
        self.avg_price = float('0'+ avg_price.strip('¢-'))/100
        self.sell = float(sell.strip('¢'))/100

But the example I wrote monitors prices (and displays updated prices, I omitted that part) for each contract in the array of contracts.

**Comment by kcinnick** [comment]
Okay, so what happened is that they changed the internal reference to long and short types on the sell side but not on the buy side. Fixed it up as of writing this comment, tested it on my side - wasted about 16 cents but it's worth it for peace of mind :-)

**Comment by Staaaaaaaaaan** [comment]
I think something similar may have happened on the buy side now... Going to e.g. https://www.predictit.org/Trade/LoadBuylong?contractId=6102 provides a 404 while the corresponding sell market https://www.predictit.org/Trade/LoadSellLong?contractId=6102 still exists. Not sure how to access the buy side now though... Any ideas on how to find the new reference? 
Thanks for all of this btw! Very cool project!
