### ISSUE TITLE
Help with Install

### ISSUE THREAD

**Issue by jshwvr** [kcinnick/pyredictit#2]
I'm probably just dumb.

I installed python3.6, installed mechanicalsoup, cloned your repo to my OSX desktop, ran python3.6 check_balances.py after putting in my credentials and deleting the sample outputs. Getting this error:

`python3.6 check_balances.py 
Traceback (most recent call last):
  File "check_balances.py", line 1, in <module>
    from pyredictit.pyredictit import pyredictit
ModuleNotFoundError: No module named 'pyredictit'`

Help?

**Comment by kcinnick** [comment]
hey jshwvr thanks for trying out the module.  Are you running Python (or a Python script) in the same directory as where you placed the module? i.e., if you created a fresh directory and cloned the repo, are you running Python or a Python script from that same fresh directory?

**Comment by kcinnick** [comment]
i.e. the directory hierarchy has to be like so: [http://imgur.com/a/Re3hg](url).  Does that make sense?

**Comment by jshwvr** [comment]
Nick,

Thanks for the help. Here’s what I’ve got. I didn’t know if it mattered, so I copied the check_balances.py script out of the examples folder when I plugged in my credentials. 




and:



Cheers,

JW

**Comment by kcinnick** [comment]
Could you try posting those images again? Doesn't look like they went through properly

**Comment by jshwvr** [comment]
<img width="521" alt="screen shot 2017-01-26 at 12 08 33 pm" src="https://cloud.githubusercontent.com/assets/22228084/22344141/9c858cc4-e3c0-11e6-898b-ec5c383ecc45.png">
<img width="830" alt="screen shot 2017-01-26 at 12 04 01 pm" src="https://cloud.githubusercontent.com/assets/22228084/22344142/9c85cb4e-e3c0-11e6-876f-0bc269fcdbf1.png">

**Comment by kcinnick** [comment]
ohh okay, I understand the problem now - check_balances.py isn't part of pyredictit, it's an example of *using* the module. so, for example, if you copy & pasted check_balances.py from where you have it to where you placed the directory like so: http://imgur.com/a/XEHR3

then type in that script's name so that your terminal looks something like this:

http://imgur.com/a/ZgzKc

then hit enter, it should work.

**Comment by jshwvr** [comment]
Getting this now:

<img width="204" alt="screen shot 2017-01-26 at 12 22 32 pm" src="https://cloud.githubusercontent.com/assets/22228084/22344573/3f7aa17a-e3c2-11e6-93ba-d92aefd84f13.png">
<img width="693" alt="screen shot 2017-01-26 at 12 23 45 pm" src="https://cloud.githubusercontent.com/assets/22228084/22344595/4fef1464-e3c2-11e6-8cf0-b1d1610e9ba1.png">

**Comment by kcinnick** [comment]
are you sure that you're using valid login credentials? It has to be the email you login with, not a username

**Comment by jshwvr** [comment]
Ahh, that fixed it. All working now. Thanks for all the help getting it running! I've been hoping someone would do a project like this for ages. Would be sweet to someday expand this into better charts/history data or something that mimicked a normal trading platform better. 

Maybe if I find some time I'll give it a shot. As you can tell, python and dealing with web APIs is not my thing. Could be fun to dabble in, though.

**Comment by kcinnick** [comment]
No problem at all! Glad we got it working :-) Yeah, my overall end-goal with this would be something like the kind of functionality that eTrade/TDAmeritrade/etc offer.  Please feel free to drop me a line if you run into any other issues or have any more questions!
