### ISSUE TITLE
Error in estimate_best_result?

### ISSUE THREAD

**Issue by Opossumist** [kcinnick/pyredictit#5]
Line 90 is producing answers that are nonsensical.

**Comment by kcinnick** [comment]
Could you send over an example of results you're getting that are nonsensical?

**Comment by kcinnick** [comment]
hey, I've tried recreating this on my end but I don't really own that many contracts and I've been unable to trigger it thus far.  I'm going to close this for now, but feel free to re-open with some example output if you're still noticing this is a problem.
