### ISSUE TITLE
Additional info needed in readme

### ISSUE THREAD

**Issue by spyjdh** [kcinnick/pyredictit#7]
Im not very familiar with how to use a python module but this is the closest I've gotten to getting it working;
C:\Users\Mjolnir\Desktop\pyredictit-master>python -m pyredictit.py
C:\Users\Mjolnir\AppData\Local\Programs\Python\Python36-32\python.exe: Error while finding module specification for 'pyredictit.py' (AttributeError: module 'pyredictit' has no attribute '__path__')

Seems like the readme is missing arguments also. Not sure where to put login credentials.

**Comment by spyjdh** [comment]
So I figured out I need to move one of the examples to the pyredictit directory and i can put my login credentials there. Now im getting this;

C:\Users\Mjolnir\Desktop\pyredictit-master>python -m check_balances.py
Traceback (most recent call last):
  File "C:\Users\Mjolnir\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Mjolnir\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Mjolnir\Desktop\pyredictit-master\check_balances.py", line 10
    >>> You've lost $2.26.
     ^
SyntaxError: invalid syntax

**Comment by spyjdh** [comment]
Okay, so it should definitely be explained that the example scripts are where you put your login credentials and that they should be run from the parent directory of pyredictit/pyredictit.py
 
Got it working, but still getting this error;

C:\Users\Mjolnir\AppData\Local\Programs\Python\Python36-32\python.exe: Error while finding module specification for 'check_balances.py' (AttributeError: module 'check_balances' has no attribute '__path__')

**Comment by kcinnick** [comment]
Lines predicated with >>> are to indicate ouput, not meant to be run from the examples dir without any changes. Sorry, I suppose that should be made more clear.  As far as the path error - what command are you using to run the script?

**Comment by spyjdh** [comment]
python -m scriptname.py

**Comment by kcinnick** [comment]
Can you try it without the -m flag:

python script_name.py

?

**Comment by spyjdh** [comment]
That worked. I don't know why I was using it before. Not used to python lol
