### ISSUE TITLE
Output formatting inconsistency in summarize current contracts

### ISSUE THREAD

**Issue by spyjdh** [kcinnick/pyredictit#8]
Your average purchase price of Yes shares is 17¢
Yes shares are currently being sold at 0.15
Yes shares are currently being bought for 14¢

**Comment by spyjdh** [comment]
can be fixed by adding .strip('¢') to         self.avg_price = avg_price
and         self.sell = sell

this will then make it easier to convert to float

**Comment by kcinnick** [comment]
thanks, will take care of this in the morning
