### ISSUE TITLE
help with stop_loss_monitoring

### ISSUE THREAD

**Issue by spyjdh** [kcinnick/pyredictit#9]
getting an error when stop loss condition is true;

Traceback (most recent call last):
  File "stop_loss_monitoring.py", line 14, in <module>
    number_of_shares=1, trigger_price=0.14)
  File "C:\Users\Forerunner\Documents\PredictIt\pyredictit\pyredictit.py", line 427, in monitor_price_of_contract
    contract.sell(api=self, number_of_shares=number_of_shares, sell_price=trigger_price)
TypeError: 'float' object is not callable

**Comment by kcinnick** [comment]
hmm.. going to check into this this afternoon and see if I can recreate it. I'm guessing that there's a missing operator in there somewhere.

**Comment by spyjdh** [comment]
Should line 427 be contract.sell_shares instead of contact.sell ? 
I'm unable to test at the moment

**Comment by kcinnick** [comment]
great catch!

**Comment by spyjdh** [comment]
If that was it, the if statement for buy_at contains a contract.buy() that also needs to be changed to contract.buy_shares()

**Comment by kcinnick** [comment]
Just committed a version with those fixes, thank you so much for noticing that stuff!
